version: '3'
services:
        htpcmanager:
                image: linuxserver/htpcmanager
                volumes:
                        - ${CONFIG_PATH}:/config
                environment:
                        PGID: ${PGID}
                        PUID: ${PUID}
                        TZ:   ${TIMEZONE}
                ports:
                        - ${PORT}:8085
